cmake_minimum_required(VERSION 4.2)
project(C__)

set(CMAKE_CXX_STANDARD 14)

add_executable(C__
        "Program/ChatBot Pro 2.0.cpp"
        "Program/Hello World.cpp"
        "Program/MinGW compile assistant.cpp"
        Program/未命名1.cpp
        Temp/main.cpp
        模板工具/dijkstra.cpp
        模板工具/st表.cpp
        模板工具/分块模版.cpp
        模板工具/并查集.cpp
        模板工具/快速幂.cpp
        模板工具/最小生成树.cpp
        模板工具/最长上升子序列（单调优化）.cpp
        模板工具/最长上升子序列（朴素DP）.cpp
        模板工具/最长公共子序列.cpp
        模板工具/泛洪.cpp
        模板工具/线段树.cpp
        模板工具/线段树封装.cpp
        模板工具/莫队算法模板P2709.cpp
        模板工具/连通块.cpp
        Temp/niam.cpp
        Program/trie.cpp
        test/random.cpp
        test/sol.cpp
        test/bf.cpp
        test/test.cpp
        Program/鼠标连点器.cpp
        contest/t3.cpp
        contest/t4.cpp
        contest/t1.cpp
        contest/t2.cpp
        模板工具/DP/背包/完全背包.cpp
        模板工具/DP/背包/完全背包.cpp
        模板工具/DP/背包/01背包.cpp
        head/segments_tree.h
        head/knapsack.h)
